// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'CAvatar.story': typeof import('./src/components/utils/g-avatar copy/CAvatar.story.vue')['default']
    GAvatar: typeof import('./src/components/utils/g-avatar/GAvatar.vue')['default']
    'GAvatar.story': typeof import('./src/components/utils/g-avatar/GAvatar.story.vue')['default']
    GCard: typeof import('./src/components/utils/g-card/GCard.vue')['default']
    'GCard.story': typeof import('./src/components/utils/g-card/GCard.story.vue')['default']
    GInput: typeof import('./src/components/forms/g-input/GInput.vue')['default']
    'GInput.story': typeof import('./src/components/forms/g-input/GInput.story.vue')['default']
    GInputsStory: typeof import('./src/components/GInputs-story.vue')['default']
    GInputStory: typeof import('./src/components/forms/g-input/GInput-story.vue')['default']
    GLoader: typeof import('./src/components/utils/g-loader/GLoader.vue')['default']
    'GLoader.story': typeof import('./src/components/utils/g-loader/GLoader.story.vue')['default']
    GTag: typeof import('./src/components/utils/g-tag/GTag.vue')['default']
    'GTag.story': typeof import('./src/components/utils/g-tag/GTag.story.vue')['default']
    'GTag.stoyr': typeof import('./src/components/g-tag/GTag.stoyr.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IAkarIcons:googleFill': typeof import('~icons/akar-icons/google-fill')['default']
    IEosIconsBubbleLoading: typeof import('~icons/eos-icons/bubble-loading')['default']
    'IEva:closeCircleOutline': typeof import('~icons/eva/close-circle-outline')['default']
    'IEva:closeOutline': typeof import('~icons/eva/close-outline')['default']
    LanguageSwitcher: typeof import('./src/components/utils/LanguageSwitcher.vue')['default']
    ToggleDark: typeof import('./src/components/utils/ToggleDark.vue')['default']
  }
}

export { }
